-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 22:39:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Contato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `Cpf_UNIQUE` (`Cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Serviço` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Data da Solicitação` DATE NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Status do Pedido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Status do Pedido`),
  INDEX `fk_Pedido_Cliente_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mecânico Responsável`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mecânico Responsável` (
  `idMecânico Responsável` INT NOT NULL,
  `Nível` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Departamento` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMecânico Responsável`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` Referência de Preços/Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` Referência de Preços/Serviço` (
  `id Referência de Preços/Serviço` INT NOT NULL,
  `Descrição` VARCHAR(45) NOT NULL,
  `Preço Peça` FLOAT NOT NULL,
  `Mecânico Responsável_idMecânico Responsável` INT NOT NULL,
  PRIMARY KEY (`id Referência de Preços/Serviço`, `Mecânico Responsável_idMecânico Responsável`),
  INDEX `fk_ Referência de Preços/Serviço_Mecânico Responsável1_idx` (`Mecânico Responsável_idMecânico Responsável` ASC) VISIBLE,
  CONSTRAINT `fk_ Referência de Preços/Serviço_Mecânico Responsável1`
    FOREIGN KEY (`Mecânico Responsável_idMecânico Responsável`)
    REFERENCES `mydb`.`Mecânico Responsável` (`idMecânico Responsável`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ordem de Serviço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ordem de Serviço` (
  `idOrdem de Serviço` INT NOT NULL,
  `Status da Ordem de Serviço` VARCHAR(45) NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Pedido_Status do Pedido` VARCHAR(45) NOT NULL,
  `Data de Emissão` DATE NOT NULL,
  `Data de conclusão` DATE NOT NULL,
  `Valor do Serviço` FLOAT NOT NULL,
  `Autorização do Cliente` VARCHAR(45) NOT NULL,
  ` Referência de Preços/Serviço_id Referência de Preços/Serviço` INT NOT NULL,
  ` Referência de Preços/Serviço_Mecânico Responsável_idMecânico Responsável` INT NOT NULL,
  PRIMARY KEY (`idOrdem de Serviço`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Pedido_Status do Pedido`, ` Referência de Preços/Serviço_id Referência de Preços/Serviço`, ` Referência de Preços/Serviço_Mecânico Responsável_idMecânico Responsável`),
  INDEX `fk_Ordem de Serviço_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC, `Pedido_Status do Pedido` ASC) VISIBLE,
  INDEX `fk_Ordem de Serviço_ Referência de Preços/Serviço1_idx` (` Referência de Preços/Serviço_id Referência de Preços/Serviço` ASC, ` Referência de Preços/Serviço_Mecânico Responsável_idMecânico Responsável` ASC) VISIBLE,
  CONSTRAINT `fk_Ordem de Serviço_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Status do Pedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente` , `Status do Pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ordem de Serviço_ Referência de Preços/Serviço1`
    FOREIGN KEY (` Referência de Preços/Serviço_id Referência de Preços/Serviço` , ` Referência de Preços/Serviço_Mecânico Responsável_idMecânico Responsável`)
    REFERENCES `mydb`.` Referência de Preços/Serviço` (`id Referência de Preços/Serviço` , `Mecânico Responsável_idMecânico Responsável`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Avaliação de Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Avaliação de Pedido` (
  `Mecânico Responsável_idMecânico Responsável` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`Mecânico Responsável_idMecânico Responsável`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`),
  INDEX `fk_Mecânico Responsável_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Mecânico Responsável_has_Pedido_Mecânico Responsável_idx` (`Mecânico Responsável_idMecânico Responsável` ASC) VISIBLE,
  CONSTRAINT `fk_Mecânico Responsável_has_Pedido_Mecânico Responsável1`
    FOREIGN KEY (`Mecânico Responsável_idMecânico Responsável`)
    REFERENCES `mydb`.`Mecânico Responsável` (`idMecânico Responsável`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mecânico Responsável_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
